spring:
  jpa:
    database: h2
    show-sql: false   # SQL 쿼리 로깅 비활성화
    hibernate:
      ddl-auto: update # 자동 스키마 생성/업데이트 설정
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:    # 타임리프 템플릿 경로 설정
    # prefix: classpath:/templates/
    # suffix: .html
    prefix: file:src/main/resources/templates/  # 개발 중에 변경사항을 바로바로 확인하기 위해서
    cache: false                                # 실제 서비스 중에는 cache를 true로 살려야 함

  datasource:
    url: jdbc:h2:file:./data/blog-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  devtools:     # 수정사항 생길시 자동 재빌드
    livereload:
      enabled: true
    restart:
      enabled: true

  mvc:          # mvc
    hiddenmethod:
      filter:
        enabled: true

  servlet:      # 파일 저장 위치
    multipart:
      enabled: true
      location: /Users/hyunrok/Git/BlogApplication/blog/src/main/resources/static/upload
      max-request-size: 215MB
      max-file-size: 200MB

  resources:
    static-locations: classpath:/static/, file:/Users/hyunrok/Git/BlogApplication/blog/src/main/resources/static/upload/

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

file:
  upload:
    relative-path: /upload/

jwt:
  issuer: sh0501sh11@gmail.com
  secret_key: blog-springboot

logging:
  level:
    org.springframework.security: DEBUG